# Generated by Django 5.2.17 on 2026-09-08 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0002_database_access'),
        ('problems', '0006_problem_processed_message_sequence'),
        ('runs', '0003_answer_event_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('goal', models.TextField()),
                ('basis_card_ids', models.JSONField()),
                ('fixed_input', models.JSONField()),
                ('revision', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='problems.problem')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.libraryrelease')),
            ],
        ),
        migrations.CreateModel(
            name='LearningTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.BigIntegerField()),
                ('kind', models.CharField(max_length=20)),
                ('content', models.JSONField()),
                ('client_message_id', models.UUIDField(blank=True, null=True)),
                ('learning_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningsession')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('responds_to_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='learning.learningturn')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='runs.analysisrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='learningsession',
            constraint=models.UniqueConstraint(fields=('owner', 'id', 'release'), name='learning_owner_release_unique'),
        ),
        migrations.AddConstraint(
            model_name='learningsession',
            constraint=models.UniqueConstraint(fields=('owner', 'id'), name='learning_owner_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='learningsession',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 0)), name='learning_revision_valid'),
        ),
        migrations.AddConstraint(
            model_name='learningsession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'archived'])), name='learning_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='learningturn',
            constraint=models.UniqueConstraint(fields=('learning_session', 'sequence'), name='learning_turn_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='learningturn',
            constraint=models.UniqueConstraint(fields=('owner', 'learning_session', 'id'), name='learning_turn_owner_session_unique'),
        ),
        migrations.AddConstraint(
            model_name='learningturn',
            constraint=models.UniqueConstraint(fields=('owner', 'learning_session', 'client_message_id'), name='learning_turn_client_unique'),
        ),
        migrations.AddConstraint(
            model_name='learningturn',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='learning_turn_sequence_valid'),
        ),
        migrations.AddConstraint(
            model_name='learningturn',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['user_request', 'explanation', 'exercise', 'user_response', 'feedback'])), name='learning_turn_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='learningturn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['user_response', 'feedback']), ('responds_to_turn__isnull', False)), models.Q(('kind__in', ['user_request', 'explanation', 'exercise']), ('responds_to_turn__isnull', True)), _connector='OR'), name='learning_turn_response_required'),
        ),
    ]
