# Generated by Django 5.2.17 on 2026-09-08 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0002_database_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staging_key', models.SlugField(max_length=80, unique=True)),
                ('storage_key', models.CharField(max_length=240)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('content_version', models.CharField(max_length=24)),
                ('book_count', models.PositiveIntegerField()),
                ('card_count', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(max_length=240)),
                ('key', models.CharField(max_length=128)),
                ('body_hash', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('response_status', models.PositiveIntegerField(default=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'operation', 'key'), name='publishing_mutation_unique')],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.UUIDField()),
                ('auth_epoch', models.PositiveBigIntegerField()),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(default='queued', max_length=12)),
                ('stage', models.CharField(default='queued', max_length=24)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(max_length=48, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledge.libraryrelease')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publishing.registeredsource')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'running', 'succeeded', 'failed'])), name='publishing_job_status_valid')],
            },
        ),
    ]
