# Generated by Django 5.2.17 on 2026-09-08 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0002_database_access'),
        ('problems', '0003_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(default='run', max_length=10)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('stage', models.CharField(default='accepted', max_length=20)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=2)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_revision', models.BigIntegerField()),
                ('kind', models.CharField(max_length=10)),
                ('access_revision', models.BigIntegerField()),
                ('auth_epoch', models.BigIntegerField()),
                ('authorization_snapshot', models.JSONField()),
                ('internal_state', models.JSONField()),
                ('internal_request', models.JSONField(blank=True, null=True)),
                ('internal_session', models.JSONField(blank=True, null=True)),
                ('internal_draft', models.JSONField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=40, null=True)),
                ('stale_at', models.DateTimeField(blank=True, null=True)),
                ('input_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='problems.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.libraryrelease')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run', to='runs.job')),
            ],
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('owner', 'id'), name='job_owner_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'run')), name='job_kind_run'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'running', 'cancel_requested', 'succeeded', 'failed', 'cancelled'])), name='job_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ['accepted', 'understanding', 'retrieving', 'evaluating', 'validating', 'composing'])), name='job_stage_valid'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('attempt__lte', models.F('max_attempts')), ('max_attempts__gte', 1)), name='job_attempt_bounds'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(fields=('owner', 'problem', 'id'), name='run_owner_problem_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(('input_revision__gte', 1)), name='run_input_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['turn', 'analysis'])), name='run_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(('access_revision__gte', 0), ('auth_epoch__gte', 0)), name='run_access_revision_valid'),
        ),
    ]
