# Generated by Django 5.2.17 on 2026-09-08 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_database_access'),
        ('learning', '0001_initial'),
        ('problems', '0006_problem_processed_message_sequence'),
        ('runs', '0003_answer_event_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analysisrun',
            name='run_kind_valid',
        ),
        migrations.RemoveConstraint(
            model_name='job',
            name='job_kind_run',
        ),
        migrations.RemoveConstraint(
            model_name='jobevent',
            name='job_event_type_valid',
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='learning_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.learningsession'),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['turn', 'analysis']), ('learning_session__isnull', True), ('problem__isnull', False)), models.Q(('input_message__isnull', True), ('kind', 'learning'), ('learning_session__isnull', False), ('problem__isnull', True)), _connector='OR'), name='run_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(fields=('owner', 'learning_session', 'id'), name='run_owner_learning_unique'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['run', 'learning'])), name='job_kind_run'),
        ),
        migrations.AddConstraint(
            model_name='jobevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['stage', 'question_ready', 'answer_ready', 'learning_ready', 'coverage_gap', 'failed', 'cancelled'])), name='job_event_type_valid'),
        ),
    ]
