# Generated by Django 5.2.17 on 2026-09-08 11:15

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0002_answer_answer_owner_id_unique'),
        ('knowledge', '0002_database_access'),
        ('problems', '0006_problem_processed_message_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_index', models.PositiveIntegerField()),
                ('status', models.CharField(default='planned', max_length=10)),
                ('observation', models.TextField(blank=True, default='')),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', '-updated_at', 'id'], name='action_owner_time')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'answer', 'action_index'), name='action_owner_answer_index'), models.CheckConstraint(condition=models.Q(('status__in', ('planned', 'doing', 'done', 'dropped'))), name='action_status_valid'), models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('observation'), 10000), name='action_observation_length')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('core_card_id', models.CharField(max_length=240)),
                ('note', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.libraryrelease')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', '-updated_at', 'id'], name='bookmark_owner_time')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'release', 'core_card_id'), name='bookmark_owner_release_card'), models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('note'), 2000), name='bookmark_note_length')],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=24)),
                ('comment', models.TextField(blank=True, default='')),
                ('review_status', models.CharField(default='new', max_length=10)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ('helpful', 'shallow', 'unclear_principle', 'wrong_source', 'other'))), name='feedback_category_valid'), models.CheckConstraint(condition=models.Q(('review_status__in', ['new', 'reviewed'])), name='feedback_review_valid'), models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('comment'), 2000), name='feedback_comment_length')],
            },
        ),
    ]
