# Generated by Django 5.2.17 on 2026-09-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_database_access'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adminaudit',
            name='admin_audit_action_valid',
        ),
        migrations.AlterField(
            model_name='adminaudit',
            name='action',
            field=models.CharField(choices=[('admin.provision', 'admin.provision'), ('admin.initialize', 'admin.initialize'), ('admin.login', 'admin.login'), ('admin.reauth', 'admin.reauth'), ('admin.logout', 'admin.logout'), ('knowledge.import', 'knowledge.import'), ('knowledge.review', 'knowledge.review'), ('knowledge.publish', 'knowledge.publish'), ('knowledge.revoke', 'knowledge.revoke'), ('grants.manage', 'grants.manage'), ('grants.revoke', 'grants.revoke')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='adminaudit',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('admin.provision', 'admin.initialize', 'admin.login', 'admin.reauth', 'admin.logout', 'knowledge.import', 'knowledge.review', 'knowledge.publish', 'knowledge.revoke', 'grants.manage', 'grants.revoke'))), name='admin_audit_action_valid'),
        ),
    ]
