# Generated by Django 5.2.17 on 2026-09-08 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
        ('problems', '0006_problem_processed_message_sequence'),
        ('runs', '0003_answer_event_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('owner', 'id'), name='answer_owner_id_unique'),
        ),
    ]
