# Generated by Django 5.2.17 on 2026-09-08 03:58

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=12)),
                ('scope', models.CharField(default='private', max_length=12)),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_version', models.CharField(max_length=24)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('storage_key', models.CharField(max_length=240)),
                ('status', models.CharField(default='staged', max_length=12)),
                ('rights_status', models.CharField(default='unreviewed', max_length=12)),
                ('rights_record_key', models.CharField(blank=True, max_length=240, null=True)),
                ('card_count', models.PositiveIntegerField(default=0)),
                ('book_count', models.PositiveIntegerField(default=0)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('metadata_schema_version', models.PositiveIntegerField(default=1)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.librarycollection')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='reader', max_length=12)),
                ('status', models.CharField(default='active', max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_library_grants', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_grants', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.libraryrelease')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('core_book_id', models.CharField(max_length=240)),
                ('title', models.TextField()),
                ('author_display', models.TextField(blank=True, null=True)),
                ('contributor_metadata', models.JSONField(default=dict)),
                ('metadata_status', models.CharField(default='partial', max_length=12)),
                ('cover_asset_key', models.CharField(blank=True, max_length=240, null=True)),
                ('description', models.TextField(blank=True)),
                ('chapter_summary', models.JSONField(default=list)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.libraryrelease')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('core_card_id', models.CharField(max_length=240)),
                ('core_book_id', models.CharField(max_length=240)),
                ('card_type', models.CharField(max_length=40)),
                ('title', models.TextField()),
                ('browse_payload', models.JSONField(default=dict)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.libraryrelease')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('core_evidence_id', models.CharField(max_length=240)),
                ('core_book_id', models.CharField(max_length=240)),
                ('chapter', models.TextField()),
                ('preview_payload', models.JSONField(default=dict)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.libraryrelease')),
            ],
        ),
        migrations.CreateModel(
            name='RightsRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_book_ids', models.JSONField(default=list)),
                ('source_description', models.TextField()),
                ('basis_type', models.CharField(max_length=20)),
                ('license_name', models.TextField(blank=True, null=True)),
                ('proof_storage_key', models.TextField(blank=True, null=True)),
                ('allowed_audience', models.TextField()),
                ('allowed_uses', models.JSONField(default=list)),
                ('quote_policy', models.JSONField(default=dict)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='unreviewed', max_length=12)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rights_records', to='knowledge.libraryrelease')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='librarycollection',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'suspended'])), name='knowledge_collection_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='librarycollection',
            constraint=models.CheckConstraint(condition=models.Q(('scope__in', ['demo', 'licensed', 'private'])), name='knowledge_collection_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='libraryrelease',
            constraint=models.UniqueConstraint(fields=('library', 'content_version'), name='knowledge_release_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='libraryrelease',
            constraint=models.CheckConstraint(condition=models.Q(('content_version__regex', '^[0-9a-f]{24}$'), ('source_fingerprint__regex', '^[0-9a-f]{64}$')), name='knowledge_release_fingerprint_valid'),
        ),
        migrations.AddConstraint(
            model_name='libraryrelease',
            constraint=models.CheckConstraint(condition=models.Q(('content_version', django.db.models.functions.text.Substr('source_fingerprint', 1, 24))), name='knowledge_release_version_matches'),
        ),
        migrations.AddConstraint(
            model_name='libraryrelease',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['staged', 'validated', 'published', 'revoked'])), name='knowledge_release_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='libraryrelease',
            constraint=models.CheckConstraint(condition=models.Q(('rights_status__in', ['unreviewed', 'approved', 'rejected', 'expired'])), name='knowledge_release_rights_state'),
        ),
        migrations.AddConstraint(
            model_name='libraryrelease',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), models.Q(('book_count__gt', 0), ('card_count__gt', 0), ('published_at__isnull', False), ('rights_status', 'approved'), ('validated_at__isnull', False)), _connector='OR'), name='knowledge_release_publish_ready'),
        ),
        migrations.AddConstraint(
            model_name='librarygrant',
            constraint=models.UniqueConstraint(fields=('owner', 'release'), name='knowledge_grant_owner_release_unique'),
        ),
        migrations.AddConstraint(
            model_name='librarygrant',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'reader')), name='knowledge_grant_role_reader'),
        ),
        migrations.AddConstraint(
            model_name='librarygrant',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'revoked'])), name='knowledge_grant_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='librarygrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('status', 'revoked')), _connector='OR'), name='knowledge_grant_revocation_matches'),
        ),
        migrations.AddConstraint(
            model_name='releasebook',
            constraint=models.UniqueConstraint(fields=('release', 'core_book_id'), name='knowledge_book_release_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='releasebook',
            constraint=models.CheckConstraint(condition=models.Q(('metadata_status__in', ['verified', 'partial'])), name='knowledge_book_metadata_valid'),
        ),
        migrations.AddConstraint(
            model_name='releasecard',
            constraint=models.UniqueConstraint(fields=('release', 'core_card_id'), name='knowledge_card_release_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='releaseevidence',
            constraint=models.UniqueConstraint(fields=('release', 'core_evidence_id'), name='knowledge_evidence_release_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='rightsrecord',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['unreviewed', 'approved', 'rejected', 'expired'])), name='knowledge_rights_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='rightsrecord',
            constraint=models.CheckConstraint(condition=models.Q(('basis_type__in', ['self_authored', 'public_domain', 'license', 'permission', 'other'])), name='knowledge_rights_basis_valid'),
        ),
        migrations.AddConstraint(
            model_name='rightsrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), models.Q(('reviewed_at__isnull', False), ('reviewer__isnull', False)), _connector='OR'), name='knowledge_rights_review_required'),
        ),
    ]
