# Generated by Django 5.2.17 on 2026-09-08 10:05

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runs', '0002_jobevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField()),
                ('limit_runs', models.BigIntegerField()),
                ('reserved_runs', models.BigIntegerField(default=0)),
                ('settled_runs', models.BigIntegerField(default=0)),
                ('revision', models.BigIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RunReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default='reserved', max_length=10)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.quotabucket')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='runs.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='UsageEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.PositiveSmallIntegerField()),
                ('call_index', models.PositiveSmallIntegerField()),
                ('purpose', models.CharField(max_length=24)),
                ('provider', models.CharField(blank=True, max_length=240, null=True)),
                ('model', models.CharField(blank=True, max_length=240, null=True)),
                ('input_tokens', models.BigIntegerField(blank=True, null=True)),
                ('output_tokens', models.BigIntegerField(blank=True, null=True)),
                ('cached_tokens', models.BigIntegerField(blank=True, null=True)),
                ('duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('prompt_version', models.CharField(max_length=64)),
                ('usage_status', models.CharField(default='reserved', max_length=10)),
                ('cost_kind', models.CharField(default='unknown', max_length=10)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.analysisrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quotabucket',
            constraint=models.UniqueConstraint(fields=('owner', 'period'), name='quota_owner_period_unique'),
        ),
        migrations.AddConstraint(
            model_name='quotabucket',
            constraint=models.UniqueConstraint(fields=('owner', 'id'), name='quota_owner_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='quotabucket',
            constraint=models.CheckConstraint(condition=models.Q(('period__day', 1)), name='quota_month_start'),
        ),
        migrations.AddConstraint(
            model_name='quotabucket',
            constraint=models.CheckConstraint(condition=models.Q(('limit_runs__gte', 0), ('reserved_runs__gte', 0), ('revision__gte', 0), ('settled_runs__gte', 0), ('limit_runs__gte', django.db.models.expressions.CombinedExpression(models.F('reserved_runs'), '+', models.F('settled_runs')))), name='quota_totals_valid'),
        ),
        migrations.AddConstraint(
            model_name='runreservation',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['reserved', 'settled', 'released'])), name='reservation_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='usageentry',
            constraint=models.UniqueConstraint(fields=('owner', 'run', 'attempt', 'call_index'), name='usage_call_unique'),
        ),
        migrations.AddConstraint(
            model_name='usageentry',
            constraint=models.CheckConstraint(condition=models.Q(('attempt__gte', 1), ('call_index__gte', 1), ('call_index__lte', 24)), name='usage_call_bounds'),
        ),
        migrations.AddConstraint(
            model_name='usageentry',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ['extract', 'plan', 'analysis', 'analysis_repair'])), name='usage_purpose_valid'),
        ),
        migrations.AddConstraint(
            model_name='usageentry',
            constraint=models.CheckConstraint(condition=models.Q(('prompt_version__regex', '^[0-9a-f]{64}$')), name='usage_prompt_hash'),
        ),
        migrations.AddConstraint(
            model_name='usageentry',
            constraint=models.CheckConstraint(condition=models.Q(('usage_status__in', ['reserved', 'settled'])), name='usage_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='usageentry',
            constraint=models.CheckConstraint(condition=models.Q(('cost_amount__isnull', True), ('cost_kind', 'unknown'), ('currency__isnull', True)), name='usage_cost_unknown'),
        ),
        migrations.AddConstraint(
            model_name='usageentry',
            constraint=models.CheckConstraint(condition=models.Q(('input_tokens__isnull', True), ('input_tokens__gte', 0), _connector='OR'), name='usage_input_tokens_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='usageentry',
            constraint=models.CheckConstraint(condition=models.Q(('output_tokens__isnull', True), ('output_tokens__gte', 0), _connector='OR'), name='usage_output_tokens_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='usageentry',
            constraint=models.CheckConstraint(condition=models.Q(('cached_tokens__isnull', True), ('cached_tokens__gte', 0), _connector='OR'), name='usage_cached_tokens_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='usageentry',
            constraint=models.CheckConstraint(condition=models.Q(('duration_ms__isnull', True), ('duration_ms__gte', 0), _connector='OR'), name='usage_duration_ms_nonnegative'),
        ),
    ]
