# Generated by Django 5.2.17 on 2026-09-08 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_database_access'),
        ('runs', '0003_answer_event_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usageentry',
            name='usage_purpose_valid',
        ),
        migrations.AddConstraint(
            model_name='usageentry',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ['extract', 'plan', 'analysis', 'analysis_repair', 'learning'])), name='usage_purpose_valid'),
        ),
    ]
