# Generated by Django 5.2.17 on 2026-09-08 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_admin_projections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetainedUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField()),
                ('call_count', models.PositiveIntegerField()),
                ('input_tokens', models.BigIntegerField(null=True)),
                ('output_tokens', models.BigIntegerField(null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(max_length=16)),
                ('status', models.CharField(default='queued', max_length=10)),
                ('auth_epoch', models.PositiveBigIntegerField()),
                ('access_revision', models.PositiveBigIntegerField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('deadline', models.DateTimeField()),
                ('expires_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(max_length=40, null=True)),
                ('binding', models.JSONField(default=dict)),
                ('file_key', models.CharField(blank=True, default='', max_length=100)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('scope__in', ['problems', 'learning', 'all_personal'])), name='export_scope_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'running', 'ready', 'failed', 'expired'])), name='export_status_valid'), models.CheckConstraint(condition=models.Q(('attempts__lte', 3)), name='export_attempts_valid')],
            },
        ),
    ]
