# Generated by Django 5.2.17 on 2026-09-08 08:40

import django.db.models.deletion
from django.db.models.functions import Length
from django.db.models.lookups import GreaterThanOrEqual, LessThanOrEqual
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0002_database_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=10)),
                ('route_scope', models.CharField(max_length=240)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='processing', max_length=10)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=40, null=True)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'method', 'route_scope', 'key'), name='problem_idempotency_unique'), models.CheckConstraint(condition=models.Q(('status__in', ['processing', 'completed'])), name='problem_idempotency_status'), models.CheckConstraint(condition=models.Q(('request_hash__regex', '^[0-9a-f]{64}$')), name='problem_idempotency_hash')],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('original_question', models.TextField()),
                ('goal', models.CharField(max_length=10)),
                ('core_problem_id', models.CharField(max_length=40, unique=True)),
                ('core_state', models.JSONField()),
                ('revision', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.libraryrelease')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'status', '-updated_at', 'id'], name='problem_owner_status_updated')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'id'), name='problem_owner_id_unique'), models.CheckConstraint(condition=models.Q(('title__regex', '\\S')), name='problem_title_nonblank'), models.CheckConstraint(condition=models.Q(GreaterThanOrEqual(Length('original_question'), 1), LessThanOrEqual(Length('original_question'), 4000)), name='problem_question_length'), models.CheckConstraint(condition=models.Q(('goal__in', ['explain', 'analyze', 'compare', 'act', 'review'])), name='problem_goal_valid'), models.CheckConstraint(condition=models.Q(('revision__gte', 0)), name='problem_revision_nonnegative'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'archived', 'deleted'])), name='problem_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', False), ('status', 'deleted')), models.Q(('deleted_at__isnull', True), ('status__in', ['active', 'archived'])), _connector='OR'), name='problem_deleted_matches')],
            },
        ),
    ]
