# Generated by Django 5.2.17 on 2026-09-08 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_database_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.BigIntegerField()),
                ('role', models.CharField(max_length=10)),
                ('kind', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('client_message_id', models.UUIDField(blank=True, null=True)),
                ('intent', models.CharField(default='unknown', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(default='visible', max_length=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
        ),
    ]
