# Generated by Django 5.2.17 on 2026-09-08 09:17

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_message'),
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runs.analysisrun'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('problem', 'sequence'), name='message_problem_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('owner', 'problem', 'client_message_id'), name='message_client_unique'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('owner', 'problem', 'id'), name='message_owner_problem_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='message_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['user', 'assistant'])), name='message_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['user_text', 'clarification', 'answer', 'notice'])), name='message_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('intent__in', ['answer', 'supplement', 'analyze_now', 'unknown'])), name='message_intent_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['visible', 'withdrawn'])), name='message_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('content__regex', '\\S')), name='message_content_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'assistant'), models.Q(django.db.models.lookups.GreaterThanOrEqual(django.db.models.functions.text.Length('content'), 1), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('content'), 20000)), _connector='OR'), name='message_user_length'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'assistant'), ('kind', 'user_text'), _connector='OR'), name='message_user_kind'),
        ),
    ]
